version: '3'

services: 
  app: 
    build: .
    depends_on: 
      - mysql
  
  mysql:
    # TODO: Ver de usar mysql:8, el driver de typeorm todavía no está actualizado con el nuevo tipo de logueo de V8
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}

volumes:
  mysql-data: