export enum configuration {
  PORT = 'PORT',
  MYSQL_SSL = 'MYSQL_SSL',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
}