export enum configuration {
  PORT = 'PORT',
  MYSQL_SSL = 'MYSQL_SSL',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  HASH_ROUNDS = 'HASH_ROUNDS',
  JWT_SECRET = 'JWT_SECRET',
  JWT_COOKIE_NAME = 'JWT_COOKIE_NAME'
}